apiVersion: v2
name: trustdidweb-server-py
icon: https://identity.foundation/trustdidweb/tdw.jpg
description: An api server to register and serve trusted web dids.
type: application
version: 0.0.3
appVersion: "v0.0.2"

dependencies:
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
  - name: common
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - bitnami-common
    version: 2.x.x