---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- if .Values.ingress.labels }}  
    {{- toYaml .Values.ingress.labels | nindent 4 }}
    {{- end }}
    {{- include "server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.server.host | quote }}
    secretName: {{ .Values.fullnameOverride }}-tls
  {{- end }}
  rules:
  - host: {{ .Values.server.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "server.fullname" . }}
            port:
              number: {{ .Values.server.service.servicePort }}
        path: /
        pathType: ImplementationSpecific